# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Job:
  fields:
    list: title, datejob
    form: title, description, datejob
  order_by: 
  relationships: 
  filters: 
  search: title
  application: palsofa


