# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Image:
  fields:
    list: description, image, section
    form: description, image_file_name
  order_by: 
  relationships: 
  filters: 
  search: 
  application: palsofa
  description: Manejador de imagenes



Tienda:
  fields:
    list: nombre, direccion, telefono, horario, urls
    form: nombre, direccion, telefono, horario, urls
  order_by: 
  relationships: images
  filters: 
  search: nombre, direccion
  application: palsofa
  description: Manejador de las distintas tiendas

