

Product:
  fields:
    list: name, price
    form: name, description, price
  order_by: 
  relationships: images
  filters: 
  search: name
  application: palsofa
  description: Productos ofrecidos en la web

