# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Page:
  fields:
    list: name, permalink
    form: name, description, permalink
  order_by: 
  relationships: 
  filters: 
  search: name
  application: palsofa

Product:
  fields:
    list: name, price
    form: name, description, price, other
  order_by: 
  relationships: images
  filters: 
  search: name
  application: palsofa

