

Product:
  fields:
    list: name, price
    form: name, description, price, other, category_list, special_list
  order_by: 
  relationships: images
  filters: 
  search: name
  application: palsofa

